---
name: Checks

on: [push]

jobs: 
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
      - name: Checkout
        uses: actions/checkout@v2
      - name: Criar arquivo .env temporário
        run: |
          echo "DATABASE_URL=postgres://user:password@localhost/db" > dotenv_files/.env
          echo "API_KEY=abc123" >> dotenv_files/.env
      - name: Tests
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"